import { fileURLToPath } from "node:url";
import { drizzle, type DrizzleD1Database } from "drizzle-orm/d1";
import { migrate } from "drizzle-orm/d1/migrator";

/**
 * The folder containing the versioned migrations generated by `drizzle-kit
 * generate`. Resolved relative to this module so it is stable regardless of
 * the process working directory.
 */
export const migrationsFolder = fileURLToPath(new URL("../drizzle", import.meta.url).href);

/**
 * Apply all pending domain migrations to a D1 database and return a drizzle
 * client over it.
 *
 * Runs the versioned SQL migrations in `drizzle/` (see `drizzle.config.ts`)
 * against the given binding. Already-applied migrations are tracked in the
 * `__drizzle_migrations` table, so this is safe to run repeatedly — it only
 * applies what is missing.
 *
 * @param dbBinding the D1 binding from `env.devDb`
 */
export async function runMigrations(dbBinding: D1Database): Promise<DrizzleD1Database> {
  const db = drizzle(dbBinding);
  await migrate(db, { migrationsFolder });
  return db;
}
